# Praktikum 2 - Pra Pengolahan Data: Seleksi Fitur

**Mata Kuliah:** Pembelajaran Mesin
**Jobsheet 03:** Ekstraksi Fitur

### Tujuan Praktikum:
1. Melakukan pra-pengolahan: encoding `Sex` dan `Cabin`, imputasi `Age`, dan standardisasi `Age`.
2. Melakukan seleksi fitur untuk menyaring atribut-atribut prediktor utama.

## Langkah 1 - Load Data

In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

data_path = r'..\Dataset\Titanic-Dataset.csv'

df = pd.read_csv(data_path)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Langkah 2 - Encoding Fitur 'Sex' (Binary Mapping)

In [2]:
# Encoding 'Sex': male -> 1, female -> 0
df['Sex'] = df['Sex'].map({'male': 1, 'female': 0})
print('=== Hasil Setelah Encoding Sex ===')
df[['Sex']].head()

=== Hasil Setelah Encoding Sex ===

   Sex
0    1
1    0
2    0
3    0
4    1

## Langkah 3 - Encoding Fitur 'Cabin' (Deck Extraction & Imputasi)

In [3]:
df['Cabin'] = df['Cabin'].fillna('Unknown')
df['Cabin'] = df['Cabin'].apply(lambda x: x[0] if x != 'Unknown' else 'U')
print('=== Hasil Setelah Encoding Deck Kabin ===')
df[['Cabin']].head(10)

=== Hasil Setelah Encoding Deck Kabin ===

  Cabin
0     U
1     C
2     U
3     C
4     U
5     U
6     E
7     U
8     U
9     U

## Langkah 4 - Imputasi Fitur 'Age' dengan Median

In [4]:
df['Age'] = df['Age'].fillna(df['Age'].median())
print('=== Hasil Setelah Imputasi Usia (Median) ===')
df[['Age']].head(10)

=== Hasil Setelah Imputasi Usia (Median) ===

    Age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0
5  28.0
6  54.0
7   2.0
8  27.0
9  14.0

## Langkah 5 - Standardisasi Fitur 'Age'

In [5]:
scaler = StandardScaler()
df['Age'] = scaler.fit_transform(df[['Age']])
print('=== Hasil Setelah Standardisasi Age ===')
df[['Age']].head(10)

=== Hasil Setelah Standardisasi Age ===

        Age
0 -0.565736
1  0.663861
2 -0.258337
3  0.433312
4  0.433312
5 -0.104637
6  1.893459
7 -2.102733
8 -0.181487
9 -1.180535

## Langkah 6 - Verifikasi Data Keseluruhan Setelah Preprocessing

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,-0.565736,1,0,A/5 21171,7.2500,U,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,0.663861,1,0,PC 17599,71.2833,C,C
2,3,1,3,"Heikkinen, Miss. Laina",0,-0.258337,0,0,STON/O2. 3101282,7.9250,U,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,0.433312,1,0,113803,53.1000,C,S
4,5,0,3,"Allen, Mr. William Henry",1,0.433312,0,0,373450,8.0500,U,S

## Langkah 7 - Seleksi Fitur
Memilih fitur-fitur yang paling representatif untuk klasifikasi keselamatan:
`['Survived', 'Pclass', 'Age', 'Sex', 'Cabin']`

In [7]:
df_selected = df[['Survived', 'Pclass', 'Age', 'Sex', 'Cabin']]
print('=== Hasil Dataset Setelah Seleksi Fitur ===')
df_selected.head()

=== Hasil Dataset Setelah Seleksi Fitur ===

   Survived  Pclass       Age  Sex Cabin
0         0       3 -0.565736    1     U
1         1       1  0.663861    0     C
2         1       3 -0.258337    0     U
3         1       1  0.433312    0     C
4         0       3  0.433312    1     U